# Generated by Django 5.2.11 on 2026-06-11 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('sigip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ministry',
            field=models.ForeignKey(blank=True, help_text='Ministério do agente (obrigatório para o papel Agente Ministerial)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='sigip.ministry', verbose_name='Ministério'),
        ),
    ]
