# Generated by Django 5.2.11 on 2026-06-10 17:34

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseNature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('label', models.CharField(max_length=255, verbose_name='Denominação')),
            ],
            options={
                'verbose_name': 'Natureza da Despesa',
                'verbose_name_plural': 'Naturezas da Despesa',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Financier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome')),
                ('short_name', models.CharField(blank=True, max_length=50, verbose_name='Sigla')),
                ('type', models.CharField(choices=[('ESTADO', 'Estado (Contribuição Nacional)'), ('BILATERAL', 'Bilateral'), ('MULTILATERAL', 'Multilateral'), ('UN_AGENCY', 'Agência ONU'), ('PPP', 'Parceria Público-Privada'), ('OTHER', 'Outro')], default='OTHER', max_length=20, verbose_name='Tipo')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='País')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
            ],
            options={
                'verbose_name': 'Financiador',
                'verbose_name_plural': 'Financiadores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GovPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Denominação')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Prioridade Governamental',
                'verbose_name_plural': 'Prioridades Governamentais',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='Pillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('label', models.CharField(max_length=255, verbose_name='Denominação')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
            ],
            options={
                'verbose_name': 'Pilar PND',
                'verbose_name_plural': 'Pilares PND',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='PIPVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_year', models.IntegerField(unique=True, verbose_name='Ano de Revisão')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('REVIEW', 'Em Revisão'), ('ADOPTED', 'Adoptado'), ('ARCHIVED', 'Arquivado')], default='DRAFT', max_length=20, verbose_name='Estado')),
                ('adoption_date', models.DateField(blank=True, null=True, verbose_name='Data de Adopção')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Versão do PIP',
                'verbose_name_plural': 'Versões do PIP',
                'ordering': ['-revision_year'],
            },
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome')),
                ('short_name', models.CharField(blank=True, max_length=30, verbose_name='Sigla')),
                ('gov_priority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ministries', to='sigip.govpriority', verbose_name='Prioridade Governamental')),
                ('pillar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ministries', to='sigip.pillar', verbose_name='Pilar')),
            ],
            options={
                'verbose_name': 'Ministério',
                'verbose_name_plural': 'Ministérios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Código único do projecto (ex.: 111920101)', max_length=20, unique=True, verbose_name='Código')),
                ('title', models.CharField(max_length=500, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('is_national', models.BooleanField(default=True, verbose_name='Nacional')),
                ('status', models.CharField(choices=[('IDENTIFIED', 'Identificado'), ('IN_PROGRESS', 'Em Execução'), ('COMPLETED', 'Concluído'), ('SUSPENDED', 'Suspenso'), ('CANCELLED', 'Cancelado')], default='IDENTIFIED', max_length=20, verbose_name='Estado')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Montante total em FCFA', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Custo Total (FCFA)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado em')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Eliminado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('expense_nature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='sigip.expensenature', verbose_name='Natureza da Despesa')),
                ('gov_priority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='sigip.govpriority', verbose_name='Prioridade Governamental')),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='sigip.ministry', verbose_name='Ministério')),
                ('pillar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='sigip.pillar', verbose_name='Pilar PND')),
                ('principal_financier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='led_projects', to='sigip.financier', verbose_name='Financiador Principal')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.region', verbose_name='Região')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.tenant', verbose_name='Instituição')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
            ],
            options={
                'verbose_name': 'Projecto',
                'verbose_name_plural': 'Projectos',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PPProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_partner', models.CharField(max_length=255, verbose_name='Parceiro Privado')),
                ('structure', models.CharField(blank=True, max_length=255, verbose_name='Estrutura/Modalidade')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montante (FCFA)')),
                ('signing_date', models.DateField(blank=True, null=True, verbose_name='Data de Assinatura')),
                ('duration_years', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duração (anos)')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ppp_info', to='sigip.project', verbose_name='Projecto PIP associado')),
            ],
            options={
                'verbose_name': 'Projecto PPP',
                'verbose_name_plural': 'Projectos PPP',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('label', models.CharField(max_length=255, verbose_name='Denominação')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_sectors', to='sigip.sector', verbose_name='Sector pai')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='sigip.sector', verbose_name='Sector'),
        ),
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.IntegerField(verbose_name='Ano Fiscal')),
                ('period', models.CharField(choices=[('Q1', '1º Trimestre'), ('Q2', '2º Trimestre'), ('Q3', '3º Trimestre'), ('Q4', '4º Trimestre'), ('ANNUAL', 'Anual')], default='ANNUAL', max_length=10, verbose_name='Período')),
                ('programmed_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montante Programado (FCFA)')),
                ('actual_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montante Realizado (FCFA)')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Data do Desembolso')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('financier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursements', to='sigip.financier', verbose_name='Financiador')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='sigip.project', verbose_name='Projecto')),
            ],
            options={
                'verbose_name': 'Desembolso',
                'verbose_name_plural': 'Desembolsos',
                'ordering': ['project', 'fiscal_year', 'period'],
                'indexes': [models.Index(fields=['project', 'fiscal_year'], name='sigip_disbu_project_272ca6_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnnualProgramming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.IntegerField(help_text='Ano de programação (2026-2030)', verbose_name='Ano Fiscal')),
                ('donations', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Donativos (FCFA)')),
                ('loans', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Empréstimos (FCFA)')),
                ('state_contribution', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Contribuição do Estado (FCFA)')),
                ('version', models.IntegerField(default=1, verbose_name='Versão')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_programmings', to='sigip.project', verbose_name='Projecto')),
            ],
            options={
                'verbose_name': 'Programação Anual',
                'verbose_name_plural': 'Programações Anuais',
                'ordering': ['project', 'fiscal_year'],
                'indexes': [models.Index(fields=['fiscal_year'], name='sigip_annua_fiscal__95a72d_idx'), models.Index(fields=['project', 'fiscal_year'], name='sigip_annua_project_af7430_idx')],
                'unique_together': {('project', 'fiscal_year', 'version')},
            },
        ),
        migrations.CreateModel(
            name='ProjectFinancier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PRINCIPAL', 'Principal'), ('COFINANCER', 'Co-Financiador')], default='COFINANCER', max_length=20, verbose_name='Papel')),
                ('financier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_financiers', to='sigip.financier', verbose_name='Financiador')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_financiers', to='sigip.project', verbose_name='Projecto')),
            ],
            options={
                'verbose_name': 'Financiador do Projecto',
                'verbose_name_plural': 'Financiadores do Projecto',
                'unique_together': {('project', 'financier')},
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['ministry', 'status'], name='sigip_proje_ministr_8ce6ef_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['pillar', 'sector'], name='sigip_proje_pillar__e229a5_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_deleted'], name='sigip_proje_is_dele_8df94a_idx'),
        ),
    ]
