# Generated by Django 5.2.11 on 2026-06-11 06:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_ministry'),
        ('sigip', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='rejection_note',
            field=models.TextField(blank=True, help_text='Motivo de devolução preenchido pela DGP', verbose_name='Nota de Rejeição'),
        ),
        migrations.AddField(
            model_name='project',
            name='workflow_status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('SUBMETIDO', 'Submetido'), ('VALIDADO', 'Validado')], db_index=True, default='RASCUNHO', help_text='Rascunho → Submetido (pelo ministério) → Validado (pela DGP)', max_length=20, verbose_name='Estado de Validação'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['ministry', 'workflow_status'], name='sigip_proje_ministr_a4117f_idx'),
        ),
    ]
