# Generated by Django 5.2.11 on 2026-06-24 17:03

import django.core.validators
import django.db.models.deletion
import sigip.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigip', '0003_statefunction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursement',
            name='justification_file',
            field=models.FileField(blank=True, help_text='Recibo, factura ou documento comprovativo (PDF, imagem)', null=True, upload_to=sigip.models.disbursement_upload_path, verbose_name='Peça Justificativa'),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='rejection_note',
            field=models.TextField(blank=True, verbose_name='Nota de Rejeição'),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Submissão'),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_disbursements', to=settings.AUTH_USER_MODEL, verbose_name='Submetido por'),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Validação'),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_disbursements', to=settings.AUTH_USER_MODEL, verbose_name='Validado por'),
        ),
        migrations.AddField(
            model_name='disbursement',
            name='workflow_status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('SUBMETIDO', 'Submetido'), ('VALIDADO', 'Validado'), ('REJEITADO', 'Rejeitado')], default='RASCUNHO', max_length=20, verbose_name='Estado de Validação'),
        ),
        migrations.AlterField(
            model_name='annualprogramming',
            name='state_contribution',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Financiamento interno do Estado (FCFA)'),
        ),
        migrations.AddIndex(
            model_name='disbursement',
            index=models.Index(fields=['workflow_status'], name='sigip_disbu_workflo_616f55_idx'),
        ),
    ]
